"use strict";
//Adding Items:
//1) Add the item to items.js
//2) Add recipes to recipes.js
//3) Add the items to the menu in data.js

const recipes = [
//TEST
	// {id:'T_0', i:[], o:[{f:items.test_0, a:1}]},	
	// {id:'T_1', i:[], o:[{f:items.test_1, a:1}]},	
	// {id:'T_2', i:[], o:[{f:items.test_2, a:1}]},	
	// {id:'T_3', i:[], o:[{f:items.test_3, a:1}]},	
	// {id:'T_4', i:[{f:items.test_0, b:new Amount({Da:20})}], o:[{f:items.test_4, a:1}]},	
	// {id:'T_5', i:[{f:items.test_1, a:5}, {f:items.test_0, b:new Amount({Da:20})}], o:[{f:items.test_5, a:1}]},	
	// {id:'T_6', i:[{f:items.test_1, a:5},{f:items.test_0, a:10, b:new Amount({Da:20,pg:2})}], o:[{f:items.test_6, a:1}]},	
	// {id:'T_7', i:[{f:items.test_1, a:1}], o:[{f:items.test_7, a:1}]},	

//subatomic
	{id:'r_0', i:[], o:[{f:items.Q_Up, a:1}]},
	{id:'r_1', i:[], o:[{f:items.Q_Down, a:1}]},
	{id:'r_2', i:[], o:[{f:items.Electron, a:1}]},
	{id:'r_3', i:[], o:[{f:items.Photon, a:1}]},
	{id:'r_4', i:[{f:items.Q_Up, a:2}, {f:items.Q_Down, a:1}], o:[{f:items.Proton, a:1}]},
	{id:'r_5', i:[{f:items.Q_Up, a:1}, {f:items.Q_Down, a:2}], o:[{f:items.Neutron, a:1}]},
	{id:'r_6', i:[{f:items.Proton, a:1}, {f:items.Electron, a:1}], o:[{f:items.H1, a:1}]},
	{id:'r_7', i:[{f:items.Proton, a:1}, {f:items.Neutron, a:1}, {f:items.Electron, a:1}], o:[{f:items.H2, a:1}]},  
	{id:'r_8', i:[{f:items.Proton, a:1}, {f:items.Neutron, a:2}, {f:items.Electron, a:1}], o:[{f:items.H3, a:1}]},  
	{id:'r_9', i:[{f:items.Proton, a:2}, {f:items.Neutron, a:1}, {f:items.Electron, a:2}], o:[{f:items.He3, a:1}]},
	{id:'r_a', i:[{f:items.Proton, a:2}, {f:items.Neutron, a:2}, {f:items.Electron, a:2}], o:[{f:items.He4, a:1}]},
	{id:'r_b', i:[{f:items.Proton, a:3}, {f:items.Neutron, a:3}, {f:items.Electron, a:3}], o:[{f:items.Li6, a:1}]},
	{id:'r_c', i:[{f:items.Proton, a:3}, {f:items.Neutron, a:4}, {f:items.Electron, a:3}], o:[{f:items.Li7, a:1}]},
	{id:'r_d', i:[{f:items.Proton, a:4}, {f:items.Neutron, a:5}, {f:items.Electron, a:4}], o:[{f:items.Be9, a:1}]},
	{id:'r_e', i:[{f:items.Proton, a:5}, {f:items.Neutron, a:5}, {f:items.Electron, a:5}], o:[{f:items.B10, a:1}]},
	{id:'r_f', i:[{f:items.Proton, a:5}, {f:items.Neutron, a:6}, {f:items.Electron, a:5}], o:[{f:items.B11, a:1}]},
	{id:'r_g', i:[{f:items.Proton, a:6}, {f:items.Neutron, a:6}, {f:items.Electron, a:6}], o:[{f:items.C12, a:1}]},
	{id:'r_h', i:[{f:items.Proton, a:6}, {f:items.Neutron, a:7}, {f:items.Electron, a:6}], o:[{f:items.C13, a:1}]},
	{id:'r_i', i:[{f:items.Proton, a:7}, {f:items.Neutron, a:7}, {f:items.Electron, a:7}], o:[{f:items.N14, a:1}]},
	{id:'r_j', i:[{f:items.Proton, a:7}, {f:items.Neutron, a:8}, {f:items.Electron, a:7}], o:[{f:items.N15, a:1}]},
	{id:'r_k', i:[{f:items.Proton, a:8}, {f:items.Neutron, a:8}, {f:items.Electron, a:8}], o:[{f:items.O16, a:1}]},
	{id:'r_l', i:[{f:items.Proton, a:8}, {f:items.Neutron, a:9}, {f:items.Electron, a:8}], o:[{f:items.O17, a:1}]},
	{id:'r_m', i:[{f:items.Proton, a:8}, {f:items.Neutron, a:10}, {f:items.Electron, a:8}], o:[{f:items.O18, a:1}]},
	{id:'r_n', i:[{f:items.Proton, a:9}, {f:items.Neutron, a:10}, {f:items.Electron, a:9}], o:[{f:items.F19, a:1}]},
	{id:'r_o', i:[{f:items.Proton, a:10}, {f:items.Neutron, a:10}, {f:items.Electron, a:10}], o:[{f:items.Ne20, a:1}]},
	{id:'r_p', i:[{f:items.Proton, a:10}, {f:items.Neutron, a:11}, {f:items.Electron, a:10}], o:[{f:items.Ne21, a:1}]},
	{id:'r_q', i:[{f:items.Proton, a:10}, {f:items.Neutron, a:12}, {f:items.Electron, a:10}], o:[{f:items.Ne22, a:1}]},
	{id:'r_r', i:[{f:items.Proton, a:11}, {f:items.Neutron, a:12}, {f:items.Electron, a:11}], o:[{f:items.Na23, a:1}]},
	{id:'r_s', i:[{f:items.Proton, a:12}, {f:items.Neutron, a:12}, {f:items.Electron, a:12}], o:[{f:items.Mg24, a:1}]},
	{id:'r_t', i:[{f:items.Proton, a:12}, {f:items.Neutron, a:13}, {f:items.Electron, a:12}], o:[{f:items.Mg25, a:1}]},
	{id:'r_u', i:[{f:items.Proton, a:12}, {f:items.Neutron, a:14}, {f:items.Electron, a:12}], o:[{f:items.Mg26, a:1}]},
	{id:'r_v', i:[{f:items.Proton, a:13}, {f:items.Neutron, a:14}, {f:items.Electron, a:13}], o:[{f:items.Al27, a:1}]},
	{id:'r_w', i:[{f:items.Proton, a:14}, {f:items.Neutron, a:14}, {f:items.Electron, a:14}], o:[{f:items.Si28, a:1}]},
	{id:'r_x', i:[{f:items.Proton, a:14}, {f:items.Neutron, a:15}, {f:items.Electron, a:14}], o:[{f:items.Si29, a:1}]},
	{id:'r_y', i:[{f:items.Proton, a:14}, {f:items.Neutron, a:16}, {f:items.Electron, a:14}], o:[{f:items.Si30, a:1}]},
	{id:'r_z', i:[{f:items.Proton, a:15}, {f:items.Neutron, a:16}, {f:items.Electron, a:15}], o:[{f:items.P31, a:1}]},
	{id:'r_A', i:[{f:items.Proton, a:16}, {f:items.Neutron, a:16}, {f:items.Electron, a:16}], o:[{f:items.S32, a:1}]},
	{id:'r_B', i:[{f:items.Proton, a:16}, {f:items.Neutron, a:17}, {f:items.Electron, a:16}], o:[{f:items.S33, a:1}]},
	{id:'r_C', i:[{f:items.Proton, a:16}, {f:items.Neutron, a:18}, {f:items.Electron, a:16}], o:[{f:items.S34, a:1}]},
	{id:'r_D', i:[{f:items.Proton, a:16}, {f:items.Neutron, a:20}, {f:items.Electron, a:16}], o:[{f:items.S36, a:1}]},
	{id:'r_E', i:[{f:items.Proton, a:17}, {f:items.Neutron, a:18}, {f:items.Electron, a:17}], o:[{f:items.Cl35, a:1}]},
	{id:'r_F', i:[{f:items.Proton, a:17}, {f:items.Neutron, a:20}, {f:items.Electron, a:17}], o:[{f:items.Cl37, a:1}]},
	{id:'r_G', i:[{f:items.Proton, a:18}, {f:items.Neutron, a:18}, {f:items.Electron, a:18}], o:[{f:items.Ar36, a:1}]},
	{id:'r_H', i:[{f:items.Proton, a:18}, {f:items.Neutron, a:20}, {f:items.Electron, a:18}], o:[{f:items.Ar38, a:1}]},
	{id:'r_I', i:[{f:items.Proton, a:18}, {f:items.Neutron, a:22}, {f:items.Electron, a:18}], o:[{f:items.Ar40, a:1}]},
	{id:'r_J', i:[{f:items.Proton, a:19}, {f:items.Neutron, a:20}, {f:items.Electron, a:19}], o:[{f:items.K39, a:1}]},
	{id:'r_K', i:[{f:items.Proton, a:19}, {f:items.Neutron, a:21}, {f:items.Electron, a:19}], o:[{f:items.K40, a:1}]},
	{id:'r_L', i:[{f:items.Proton, a:19}, {f:items.Neutron, a:22}, {f:items.Electron, a:19}], o:[{f:items.K41, a:1}]},
	{id:'r_M', i:[{f:items.Proton, a:20}, {f:items.Neutron, a:20}, {f:items.Electron, a:20}], o:[{f:items.Ca40, a:1}]},
	{id:'r_N', i:[{f:items.Proton, a:20}, {f:items.Neutron, a:22}, {f:items.Electron, a:20}], o:[{f:items.Ca42, a:1}]},
	{id:'r_O', i:[{f:items.Proton, a:20}, {f:items.Neutron, a:23}, {f:items.Electron, a:20}], o:[{f:items.Ca43, a:1}]},
	{id:'r_P', i:[{f:items.Proton, a:20}, {f:items.Neutron, a:24}, {f:items.Electron, a:20}], o:[{f:items.Ca44, a:1}]},
	{id:'r_Q', i:[{f:items.Proton, a:20}, {f:items.Neutron, a:26}, {f:items.Electron, a:20}], o:[{f:items.Ca46, a:1}]},
	{id:'r_R', i:[{f:items.Proton, a:20}, {f:items.Neutron, a:28}, {f:items.Electron, a:20}], o:[{f:items.Ca48, a:1}]},
	{id:'r_S', i:[{f:items.Proton, a:21}, {f:items.Neutron, a:24}, {f:items.Electron, a:21}], o:[{f:items.Sc45, a:1}]},
	{id:'r_T', i:[{f:items.Proton, a:22}, {f:items.Neutron, a:24}, {f:items.Electron, a:22}], o:[{f:items.Ti46, a:1}]},
	{id:'r_U', i:[{f:items.Proton, a:22}, {f:items.Neutron, a:25}, {f:items.Electron, a:22}], o:[{f:items.Ti47, a:1}]},
	{id:'r_V', i:[{f:items.Proton, a:22}, {f:items.Neutron, a:26}, {f:items.Electron, a:22}], o:[{f:items.Ti48, a:1}]},
	{id:'r_W', i:[{f:items.Proton, a:22}, {f:items.Neutron, a:27}, {f:items.Electron, a:22}], o:[{f:items.Ti49, a:1}]},
	{id:'r_X', i:[{f:items.Proton, a:22}, {f:items.Neutron, a:28}, {f:items.Electron, a:22}], o:[{f:items.Ti50, a:1}]},
	{id:'r_Y', i:[{f:items.Proton, a:23}, {f:items.Neutron, a:27}, {f:items.Electron, a:23}], o:[{f:items.V50, a:1}]},
	{id:'r_Z', i:[{f:items.Proton, a:23}, {f:items.Neutron, a:28}, {f:items.Electron, a:23}], o:[{f:items.V51, a:1}]},
	{id:'r_10', i:[{f:items.Proton, a:24}, {f:items.Neutron, a:26}, {f:items.Electron, a:24}], o:[{f:items.Cr50, a:1}]},
	{id:'r_11', i:[{f:items.Proton, a:24}, {f:items.Neutron, a:28}, {f:items.Electron, a:24}], o:[{f:items.Cr52, a:1}]},
	{id:'r_12', i:[{f:items.Proton, a:24}, {f:items.Neutron, a:29}, {f:items.Electron, a:24}], o:[{f:items.Cr53, a:1}]},
	{id:'r_13', i:[{f:items.Proton, a:24}, {f:items.Neutron, a:30}, {f:items.Electron, a:24}], o:[{f:items.Cr54, a:1}]},
	{id:'r_14', i:[{f:items.Proton, a:25}, {f:items.Neutron, a:30}, {f:items.Electron, a:25}], o:[{f:items.Mn55, a:1}]},
	{id:'r_15', i:[{f:items.Proton, a:26}, {f:items.Neutron, a:28}, {f:items.Electron, a:26}], o:[{f:items.Fe54, a:1}]},
	{id:'r_16', i:[{f:items.Proton, a:26}, {f:items.Neutron, a:30}, {f:items.Electron, a:26}], o:[{f:items.Fe56, a:1}]},
	{id:'r_17', i:[{f:items.Proton, a:26}, {f:items.Neutron, a:31}, {f:items.Electron, a:26}], o:[{f:items.Fe57, a:1}]},
	{id:'r_18', i:[{f:items.Proton, a:26}, {f:items.Neutron, a:32}, {f:items.Electron, a:26}], o:[{f:items.Fe58, a:1}]},
	{id:'r_19', i:[{f:items.Proton, a:27}, {f:items.Neutron, a:32}, {f:items.Electron, a:27}], o:[{f:items.Co59, a:1}]},
	{id:'r_1a', i:[{f:items.Proton, a:28}, {f:items.Neutron, a:30}, {f:items.Electron, a:28}], o:[{f:items.Ni58, a:1}]},
	{id:'r_1b', i:[{f:items.Proton, a:28}, {f:items.Neutron, a:32}, {f:items.Electron, a:28}], o:[{f:items.Ni60, a:1}]},
	{id:'r_1c', i:[{f:items.Proton, a:28}, {f:items.Neutron, a:33}, {f:items.Electron, a:28}], o:[{f:items.Ni61, a:1}]},
	{id:'r_1d', i:[{f:items.Proton, a:28}, {f:items.Neutron, a:34}, {f:items.Electron, a:28}], o:[{f:items.Ni62, a:1}]},
	{id:'r_1e', i:[{f:items.Proton, a:28}, {f:items.Neutron, a:36}, {f:items.Electron, a:28}], o:[{f:items.Ni64, a:1}]},
	{id:'r_1f', i:[{f:items.Proton, a:29}, {f:items.Neutron, a:34}, {f:items.Electron, a:29}], o:[{f:items.Cu63, a:1}]},
	{id:'r_1g', i:[{f:items.Proton, a:29}, {f:items.Neutron, a:36}, {f:items.Electron, a:29}], o:[{f:items.Cu65, a:1}]},
	{id:'r_1h', i:[{f:items.Proton, a:30}, {f:items.Neutron, a:34}, {f:items.Electron, a:30}], o:[{f:items.Zn64, a:1}]},
	{id:'r_1i', i:[{f:items.Proton, a:30}, {f:items.Neutron, a:36}, {f:items.Electron, a:30}], o:[{f:items.Zn66, a:1}]},
	{id:'r_1j', i:[{f:items.Proton, a:30}, {f:items.Neutron, a:37}, {f:items.Electron, a:30}], o:[{f:items.Zn67, a:1}]},
	{id:'r_1k', i:[{f:items.Proton, a:30}, {f:items.Neutron, a:38}, {f:items.Electron, a:30}], o:[{f:items.Zn68, a:1}]},
	{id:'r_1l', i:[{f:items.Proton, a:30}, {f:items.Neutron, a:40}, {f:items.Electron, a:30}], o:[{f:items.Zn70, a:1}]},
	{id:'r_1m', i:[{f:items.Proton, a:31}, {f:items.Neutron, a:38}, {f:items.Electron, a:31}], o:[{f:items.Ga69, a:1}]},
	{id:'r_1n', i:[{f:items.Proton, a:31}, {f:items.Neutron, a:40}, {f:items.Electron, a:31}], o:[{f:items.Ga71, a:1}]},
	{id:'r_1o', i:[{f:items.Proton, a:32}, {f:items.Neutron, a:38}, {f:items.Electron, a:32}], o:[{f:items.Ge70, a:1}]},
	{id:'r_1p', i:[{f:items.Proton, a:32}, {f:items.Neutron, a:40}, {f:items.Electron, a:32}], o:[{f:items.Ge72, a:1}]},
	{id:'r_1q', i:[{f:items.Proton, a:32}, {f:items.Neutron, a:41}, {f:items.Electron, a:32}], o:[{f:items.Ge73, a:1}]},
	{id:'r_1r', i:[{f:items.Proton, a:32}, {f:items.Neutron, a:42}, {f:items.Electron, a:32}], o:[{f:items.Ge74, a:1}]},
	{id:'r_1s', i:[{f:items.Proton, a:32}, {f:items.Neutron, a:44}, {f:items.Electron, a:32}], o:[{f:items.Ge76, a:1}]},
	{id:'r_1t', i:[{f:items.Proton, a:33}, {f:items.Neutron, a:42}, {f:items.Electron, a:33}], o:[{f:items.As75, a:1}]},
	{id:'r_1u', i:[{f:items.Proton, a:34}, {f:items.Neutron, a:40}, {f:items.Electron, a:34}], o:[{f:items.Se74, a:1}]},
	{id:'r_1v', i:[{f:items.Proton, a:34}, {f:items.Neutron, a:42}, {f:items.Electron, a:34}], o:[{f:items.Se76, a:1}]},
	{id:'r_1w', i:[{f:items.Proton, a:34}, {f:items.Neutron, a:43}, {f:items.Electron, a:34}], o:[{f:items.Se77, a:1}]},
	{id:'r_1x', i:[{f:items.Proton, a:34}, {f:items.Neutron, a:44}, {f:items.Electron, a:34}], o:[{f:items.Se78, a:1}]},
	{id:'r_1y', i:[{f:items.Proton, a:34}, {f:items.Neutron, a:46}, {f:items.Electron, a:34}], o:[{f:items.Se80, a:1}]},
	{id:'r_1z', i:[{f:items.Proton, a:34}, {f:items.Neutron, a:48}, {f:items.Electron, a:34}], o:[{f:items.Se82, a:1}]},
	{id:'r_1A', i:[{f:items.Proton, a:35}, {f:items.Neutron, a:44}, {f:items.Electron, a:35}], o:[{f:items.Br79, a:1}]},
	{id:'r_1B', i:[{f:items.Proton, a:35}, {f:items.Neutron, a:46}, {f:items.Electron, a:35}], o:[{f:items.Br81, a:1}]},
	{id:'r_1C', i:[{f:items.Proton, a:36}, {f:items.Neutron, a:42}, {f:items.Electron, a:36}], o:[{f:items.Kr78, a:1}]},
	{id:'r_1D', i:[{f:items.Proton, a:37}, {f:items.Neutron, a:43}, {f:items.Electron, a:37}], o:[{f:items.Kr80, a:1}]},
	{id:'r_1E', i:[{f:items.Proton, a:37}, {f:items.Neutron, a:45}, {f:items.Electron, a:37}], o:[{f:items.Kr82, a:1}]},
	{id:'r_1F', i:[{f:items.Proton, a:37}, {f:items.Neutron, a:46}, {f:items.Electron, a:37}], o:[{f:items.Kr83, a:1}]},
	{id:'r_1G', i:[{f:items.Proton, a:37}, {f:items.Neutron, a:47}, {f:items.Electron, a:37}], o:[{f:items.Kr84, a:1}]},
	{id:'r_1H', i:[{f:items.Proton, a:37}, {f:items.Neutron, a:49}, {f:items.Electron, a:37}], o:[{f:items.Kr86, a:1}]},
	{id:'r_1I', i:[{f:items.Proton, a:37}, {f:items.Neutron, a:48}, {f:items.Electron, a:37}], o:[{f:items.Rb85, a:1}]},
	{id:'r_1J', i:[{f:items.Proton, a:37}, {f:items.Neutron, a:50}, {f:items.Electron, a:37}], o:[{f:items.Rb87, a:1}]},
	{id:'r_1K', i:[{f:items.Proton, a:38}, {f:items.Neutron, a:46}, {f:items.Electron, a:38}], o:[{f:items.Sr84, a:1}]},
	{id:'r_1L', i:[{f:items.Proton, a:38}, {f:items.Neutron, a:48}, {f:items.Electron, a:38}], o:[{f:items.Sr86, a:1}]},
	{id:'r_1M', i:[{f:items.Proton, a:38}, {f:items.Neutron, a:49}, {f:items.Electron, a:38}], o:[{f:items.Sr87, a:1}]},
	{id:'r_1N', i:[{f:items.Proton, a:38}, {f:items.Neutron, a:50}, {f:items.Electron, a:38}], o:[{f:items.Sr88, a:1}]},
	{id:'r_1O', i:[{f:items.Proton, a:39}, {f:items.Neutron, a:50}, {f:items.Electron, a:39}], o:[{f:items.Y89, a:1}]},
	{id:'r_1P', i:[{f:items.Proton, a:40}, {f:items.Neutron, a:50}, {f:items.Electron, a:40}], o:[{f:items.Zr90, a:1}]},
	{id:'r_1Q', i:[{f:items.Proton, a:40}, {f:items.Neutron, a:51}, {f:items.Electron, a:40}], o:[{f:items.Zr91, a:1}]},
	{id:'r_1R', i:[{f:items.Proton, a:40}, {f:items.Neutron, a:52}, {f:items.Electron, a:40}], o:[{f:items.Zr92, a:1}]},
	{id:'r_1S', i:[{f:items.Proton, a:40}, {f:items.Neutron, a:54}, {f:items.Electron, a:40}], o:[{f:items.Zr94, a:1}]},
	{id:'r_1T', i:[{f:items.Proton, a:40}, {f:items.Neutron, a:56}, {f:items.Electron, a:40}], o:[{f:items.Zr96, a:1}]},
	{id:'r_1U', i:[{f:items.Proton, a:41}, {f:items.Neutron, a:52}, {f:items.Electron, a:41}], o:[{f:items.Nb93, a:1}]},
	{id:'r_1V', i:[{f:items.Proton, a:42}, {f:items.Neutron, a:50}, {f:items.Electron, a:42}], o:[{f:items.Mo92, a:1}]},
	{id:'r_1W', i:[{f:items.Proton, a:42}, {f:items.Neutron, a:52}, {f:items.Electron, a:42}], o:[{f:items.Mo94, a:1}]},
	{id:'r_1X', i:[{f:items.Proton, a:42}, {f:items.Neutron, a:53}, {f:items.Electron, a:42}], o:[{f:items.Mo95, a:1}]},
	{id:'r_1Y', i:[{f:items.Proton, a:42}, {f:items.Neutron, a:54}, {f:items.Electron, a:42}], o:[{f:items.Mo96, a:1}]},
	{id:'r_1Z', i:[{f:items.Proton, a:42}, {f:items.Neutron, a:55}, {f:items.Electron, a:42}], o:[{f:items.Mo97, a:1}]},
	{id:'r_20', i:[{f:items.Proton, a:42}, {f:items.Neutron, a:56}, {f:items.Electron, a:42}], o:[{f:items.Mo98, a:1}]},
	{id:'r_21', i:[{f:items.Proton, a:42 }, {f:items.Neutron, a:58}, {f:items.Electron, a:42}], o:[{f:items.Mo100, a:1}]},
	{id:'r_22', i:[{f:items.Proton, a:43}, {f:items.Neutron, a:54}, {f:items.Electron, a:43}], o:[{f:items.Tc97, a:1}]},
	{id:'r_23', i:[{f:items.Proton, a:44}, {f:items.Neutron, a:52}, {f:items.Electron, a:44}], o:[{f:items.Ru96, a:1}]},
	{id:'r_24', i:[{f:items.Proton, a:44}, {f:items.Neutron, a:54}, {f:items.Electron, a:44}], o:[{f:items.Ru98, a:1}]},
	{id:'r_25', i:[{f:items.Proton, a:44}, {f:items.Neutron, a:55}, {f:items.Electron, a:44}], o:[{f:items.Ru99, a:1}]},
	{id:'r_26', i:[{f:items.Proton, a:44}, {f:items.Neutron, a:56}, {f:items.Electron, a:44}], o:[{f:items.Ru100, a:1}]},
	{id:'r_27', i:[{f:items.Proton, a:44}, {f:items.Neutron, a:57}, {f:items.Electron, a:44}], o:[{f:items.Ru101, a:1}]},
	{id:'r_28', i:[{f:items.Proton, a:44}, {f:items.Neutron, a:58}, {f:items.Electron, a:44}], o:[{f:items.Ru102, a:1}]},
	{id:'r_29', i:[{f:items.Proton, a:44}, {f:items.Neutron, a:60}, {f:items.Electron, a:44}], o:[{f:items.Ru104, a:1}]},
	{id:'r_2a', i:[{f:items.Proton, a:45}, {f:items.Neutron, a:58}, {f:items.Electron, a:45}], o:[{f:items.Rh103, a:1}]},
	{id:'r_2b', i:[{f:items.Proton, a:46}, {f:items.Neutron, a:56}, {f:items.Electron, a:46}], o:[{f:items.Pd102, a:1}]},
	{id:'r_2c', i:[{f:items.Proton, a:46}, {f:items.Neutron, a:58}, {f:items.Electron, a:46}], o:[{f:items.Pd104, a:1}]},
	{id:'r_2d', i:[{f:items.Proton, a:46}, {f:items.Neutron, a:59}, {f:items.Electron, a:46}], o:[{f:items.Pd105, a:1}]},
	{id:'r_2e', i:[{f:items.Proton, a:46}, {f:items.Neutron, a:60}, {f:items.Electron, a:46}], o:[{f:items.Pd106, a:1}]},
	{id:'r_2f', i:[{f:items.Proton, a:46}, {f:items.Neutron, a:62}, {f:items.Electron, a:46}], o:[{f:items.Pd108, a:1}]},
	{id:'r_2g', i:[{f:items.Proton, a:46}, {f:items.Neutron, a:64}, {f:items.Electron, a:46}], o:[{f:items.Pd110, a:1}]},
	{id:'r_2h', i:[{f:items.Proton, a:47}, {f:items.Neutron, a:60}, {f:items.Electron, a:47}], o:[{f:items.Ag107, a:1}]},
	{id:'r_2i', i:[{f:items.Proton, a:47}, {f:items.Neutron, a:62}, {f:items.Electron, a:47}], o:[{f:items.Ag109, a:1}]},
	{id:'r_2j', i:[{f:items.Proton, a:48}, {f:items.Neutron, a:58}, {f:items.Electron, a:48}], o:[{f:items.Cd106, a:1}]},
	{id:'r_2k', i:[{f:items.Proton, a:48}, {f:items.Neutron, a:60}, {f:items.Electron, a:48}], o:[{f:items.Cd108, a:1}]},
	{id:'r_2l', i:[{f:items.Proton, a:48}, {f:items.Neutron, a:62}, {f:items.Electron, a:48}], o:[{f:items.Cd110, a:1}]},
	{id:'r_2m', i:[{f:items.Proton, a:48}, {f:items.Neutron, a:63}, {f:items.Electron, a:48}], o:[{f:items.Cd111, a:1}]},
	{id:'r_2n', i:[{f:items.Proton, a:48}, {f:items.Neutron, a:64}, {f:items.Electron, a:48}], o:[{f:items.Cd112, a:1}]},
	{id:'r_2o', i:[{f:items.Proton, a:48}, {f:items.Neutron, a:65}, {f:items.Electron, a:48}], o:[{f:items.Cd113, a:1}]},
	{id:'r_2p', i:[{f:items.Proton, a:48}, {f:items.Neutron, a:66}, {f:items.Electron, a:48}], o:[{f:items.Cd114, a:1}]},
	{id:'r_2q', i:[{f:items.Proton, a:48}, {f:items.Neutron, a:68}, {f:items.Electron, a:48}], o:[{f:items.Cd116, a:1}]},
	{id:'r_2r', i:[{f:items.Proton, a:49}, {f:items.Neutron, a:64}, {f:items.Electron, a:49}], o:[{f:items.In113, a:1}]},
	{id:'r_2s', i:[{f:items.Proton, a:49}, {f:items.Neutron, a:66}, {f:items.Electron, a:49}], o:[{f:items.In115, a:1}]},
	{id:'r_2t', i:[{f:items.Proton, a:50}, {f:items.Neutron, a:62}, {f:items.Electron, a:50}], o:[{f:items.Sn112, a:1}]},
	{id:'r_2u', i:[{f:items.Proton, a:50}, {f:items.Neutron, a:64}, {f:items.Electron, a:50}], o:[{f:items.Sn114, a:1}]},
	{id:'r_2v', i:[{f:items.Proton, a:50}, {f:items.Neutron, a:65}, {f:items.Electron, a:50}], o:[{f:items.Sn115, a:1}]},
	{id:'r_2w', i:[{f:items.Proton, a:50}, {f:items.Neutron, a:66}, {f:items.Electron, a:50}], o:[{f:items.Sn116, a:1}]},
	{id:'r_2x', i:[{f:items.Proton, a:50}, {f:items.Neutron, a:67}, {f:items.Electron, a:50}], o:[{f:items.Sn117, a:1}]},
	{id:'r_2y', i:[{f:items.Proton, a:50}, {f:items.Neutron, a:68}, {f:items.Electron, a:50}], o:[{f:items.Sn118, a:1}]},
	{id:'r_2z', i:[{f:items.Proton, a:50}, {f:items.Neutron, a:69}, {f:items.Electron, a:50}], o:[{f:items.Sn119, a:1}]},
	{id:'r_2A', i:[{f:items.Proton, a:50}, {f:items.Neutron, a:70}, {f:items.Electron, a:50}], o:[{f:items.Sn120, a:1}]},
	{id:'r_2B', i:[{f:items.Proton, a:50}, {f:items.Neutron, a:72}, {f:items.Electron, a:50}], o:[{f:items.Sn122, a:1}]},
	{id:'r_2C', i:[{f:items.Proton, a:50}, {f:items.Neutron, a:74}, {f:items.Electron, a:50}], o:[{f:items.Sn124, a:1}]},
	{id:'r_2D', i:[{f:items.Proton, a:51}, {f:items.Neutron, a:70}, {f:items.Electron, a:51}], o:[{f:items.Sb121, a:1}]},
	{id:'r_2E', i:[{f:items.Proton, a:51}, {f:items.Neutron, a:72}, {f:items.Electron, a:51}], o:[{f:items.Sb123, a:1}]},
	{id:'r_2F', i:[{f:items.Proton, a:52}, {f:items.Neutron, a:68}, {f:items.Electron, a:52}], o:[{f:items.Te120, a:1}]},
	{id:'r_2G', i:[{f:items.Proton, a:52}, {f:items.Neutron, a:70}, {f:items.Electron, a:52}], o:[{f:items.Te122, a:1}]},
	{id:'r_2H', i:[{f:items.Proton, a:52}, {f:items.Neutron, a:71}, {f:items.Electron, a:52}], o:[{f:items.Te123, a:1}]},
	{id:'r_2I', i:[{f:items.Proton, a:52}, {f:items.Neutron, a:72}, {f:items.Electron, a:52}], o:[{f:items.Te124, a:1}]},
	{id:'r_2J', i:[{f:items.Proton, a:52}, {f:items.Neutron, a:73}, {f:items.Electron, a:52}], o:[{f:items.Te125, a:1}]},
	{id:'r_2K', i:[{f:items.Proton, a:52}, {f:items.Neutron, a:74}, {f:items.Electron, a:52}], o:[{f:items.Te126, a:1}]},
	{id:'r_2L', i:[{f:items.Proton, a:52}, {f:items.Neutron, a:76}, {f:items.Electron, a:52}], o:[{f:items.Te128, a:1}]},
	{id:'r_2M', i:[{f:items.Proton, a:52}, {f:items.Neutron, a:78}, {f:items.Electron, a:52}], o:[{f:items.Te130, a:1}]},
	{id:'r_2N', i:[{f:items.Proton, a:53}, {f:items.Neutron, a:74}, {f:items.Electron, a:53}], o:[{f:items.I127, a:1}]},
	{id:'r_2O', i:[{f:items.Proton, a:54}, {f:items.Neutron, a:70}, {f:items.Electron, a:54}], o:[{f:items.Xe124, a:1}]},
	{id:'r_2P', i:[{f:items.Proton, a:54}, {f:items.Neutron, a:72}, {f:items.Electron, a:54}], o:[{f:items.Xe126, a:1}]},
	{id:'r_2Q', i:[{f:items.Proton, a:54}, {f:items.Neutron, a:74}, {f:items.Electron, a:54}], o:[{f:items.Xe128, a:1}]},
	{id:'r_2R', i:[{f:items.Proton, a:54}, {f:items.Neutron, a:75}, {f:items.Electron, a:54}], o:[{f:items.Xe129, a:1}]},
	{id:'r_2S', i:[{f:items.Proton, a:54}, {f:items.Neutron, a:76}, {f:items.Electron, a:54}], o:[{f:items.Xe130, a:1}]},
	{id:'r_2T', i:[{f:items.Proton, a:54}, {f:items.Neutron, a:77}, {f:items.Electron, a:54}], o:[{f:items.Xe131, a:1}]},
	{id:'r_2U', i:[{f:items.Proton, a:54}, {f:items.Neutron, a:78}, {f:items.Electron, a:54}], o:[{f:items.Xe132, a:1}]},
	{id:'r_2V', i:[{f:items.Proton, a:54}, {f:items.Neutron, a:80}, {f:items.Electron, a:54}], o:[{f:items.Xe134, a:1}]},
	{id:'r_2W', i:[{f:items.Proton, a:54}, {f:items.Neutron, a:82}, {f:items.Electron, a:54}], o:[{f:items.Xe136, a:1}]},
	{id:'r_2X', i:[{f:items.Proton, a:55}, {f:items.Neutron, a:78}, {f:items.Electron, a:55}], o:[{f:items.Cs133, a:1}]},
	{id:'r_2Y', i:[{f:items.Proton, a:56}, {f:items.Neutron, a:74}, {f:items.Electron, a:56}], o:[{f:items.Ba130, a:1}]},
	{id:'r_2Z', i:[{f:items.Proton, a:56}, {f:items.Neutron, a:76}, {f:items.Electron, a:56}], o:[{f:items.Ba132, a:1}]},
	{id:'r_30', i:[{f:items.Proton, a:56}, {f:items.Neutron, a:78}, {f:items.Electron, a:56}], o:[{f:items.Ba134, a:1}]},
	{id:'r_31', i:[{f:items.Proton, a:56}, {f:items.Neutron, a:79}, {f:items.Electron, a:56}], o:[{f:items.Ba135, a:1}]},
	{id:'r_32', i:[{f:items.Proton, a:56}, {f:items.Neutron, a:80}, {f:items.Electron, a:56}], o:[{f:items.Ba136, a:1}]},
	{id:'r_33', i:[{f:items.Proton, a:56}, {f:items.Neutron, a:81}, {f:items.Electron, a:56}], o:[{f:items.Ba137, a:1}]},
	{id:'r_34', i:[{f:items.Proton, a:56}, {f:items.Neutron, a:82}, {f:items.Electron, a:56}], o:[{f:items.Ba138, a:1}]},
	{id:'r_35', i:[{f:items.Proton, a:57}, {f:items.Neutron, a:81}, {f:items.Electron, a:57}], o:[{f:items.La138, a:1}]},
	{id:'r_36', i:[{f:items.Proton, a:57}, {f:items.Neutron, a:82}, {f:items.Electron, a:57}], o:[{f:items.La139, a:1}]},
	{id:'r_37', i:[{f:items.Proton, a:58}, {f:items.Neutron, a:78}, {f:items.Electron, a:58}], o:[{f:items.Ce136, a:1}]},
	{id:'r_38', i:[{f:items.Proton, a:58}, {f:items.Neutron, a:80}, {f:items.Electron, a:58}], o:[{f:items.Ce138, a:1}]},
	{id:'r_39', i:[{f:items.Proton, a:58}, {f:items.Neutron, a:82}, {f:items.Electron, a:58}], o:[{f:items.Ce140, a:1}]},	
	{id:'r_3a', i:[{f:items.Proton, a:58}, {f:items.Neutron, a:84}, {f:items.Electron, a:58}], o:[{f:items.Ce142, a:1}]},	
	{id:'r_3b', i:[{f:items.Proton, a:59}, {f:items.Neutron, a:82}, {f:items.Electron, a:59}], o:[{f:items.Pr141, a:1}]},	
	{id:'r_3c', i:[{f:items.Proton, a:60}, {f:items.Neutron, a:82}, {f:items.Electron, a:60}], o:[{f:items.Nd142, a:1}]},	
	{id:'r_3d', i:[{f:items.Proton, a:60}, {f:items.Neutron, a:83}, {f:items.Electron, a:60}], o:[{f:items.Nd143, a:1}]},	
	{id:'r_3e', i:[{f:items.Proton, a:60}, {f:items.Neutron, a:84}, {f:items.Electron, a:60}], o:[{f:items.Nd144, a:1}]},	
	{id:'r_3f', i:[{f:items.Proton, a:60}, {f:items.Neutron, a:85}, {f:items.Electron, a:60}], o:[{f:items.Nd145, a:1}]},	
	{id:'r_3g', i:[{f:items.Proton, a:60}, {f:items.Neutron, a:86}, {f:items.Electron, a:60}], o:[{f:items.Nd146, a:1}]},	
	{id:'r_3h', i:[{f:items.Proton, a:60}, {f:items.Neutron, a:88}, {f:items.Electron, a:60}], o:[{f:items.Nd148, a:1}]},	
	{id:'r_3i', i:[{f:items.Proton, a:60}, {f:items.Neutron, a:90}, {f:items.Electron, a:60}], o:[{f:items.Nd150, a:1}]},	
	{id:'r_3j', i:[{f:items.Proton, a:61}, {f:items.Neutron, a:84}, {f:items.Electron, a:61}], o:[{f:items.Pm145, a:1}]},	
	{id:'r_3k', i:[{f:items.Proton, a:62}, {f:items.Neutron, a:82}, {f:items.Electron, a:62}], o:[{f:items.Sm144, a:1}]},	
	{id:'r_3l', i:[{f:items.Proton, a:62}, {f:items.Neutron, a:85}, {f:items.Electron, a:62}], o:[{f:items.Sm147, a:1}]},	
	{id:'r_3m', i:[{f:items.Proton, a:62}, {f:items.Neutron, a:86}, {f:items.Electron, a:62}], o:[{f:items.Sm148, a:1}]},	
	{id:'r_3n', i:[{f:items.Proton, a:62}, {f:items.Neutron, a:87}, {f:items.Electron, a:62}], o:[{f:items.Sm149, a:1}]},	
	{id:'r_3o', i:[{f:items.Proton, a:62}, {f:items.Neutron, a:88}, {f:items.Electron, a:62}], o:[{f:items.Sm150, a:1}]},	
	{id:'r_3p', i:[{f:items.Proton, a:62}, {f:items.Neutron, a:90}, {f:items.Electron, a:62}], o:[{f:items.Sm152, a:1}]},	
	{id:'r_3q', i:[{f:items.Proton, a:62}, {f:items.Neutron, a:92}, {f:items.Electron, a:62}], o:[{f:items.Sm154, a:1}]},	
	{id:'r_3r', i:[{f:items.Proton, a:63}, {f:items.Neutron, a:88}, {f:items.Electron, a:63}], o:[{f:items.Eu151, a:1}]},	
	{id:'r_3s', i:[{f:items.Proton, a:63}, {f:items.Neutron, a:90}, {f:items.Electron, a:63}], o:[{f:items.Eu153, a:1}]},	
	{id:'r_3t', i:[{f:items.Proton, a:64}, {f:items.Neutron, a:88}, {f:items.Electron, a:64}], o:[{f:items.Gd152, a:1}]},	
	{id:'r_3u', i:[{f:items.Proton, a:64}, {f:items.Neutron, a:90}, {f:items.Electron, a:64}], o:[{f:items.Gd154, a:1}]},	
	{id:'r_3v', i:[{f:items.Proton, a:64}, {f:items.Neutron, a:91}, {f:items.Electron, a:64}], o:[{f:items.Gd155, a:1}]},	
	{id:'r_3w', i:[{f:items.Proton, a:64}, {f:items.Neutron, a:92}, {f:items.Electron, a:64}], o:[{f:items.Gd156, a:1}]},	
	{id:'r_3x', i:[{f:items.Proton, a:64}, {f:items.Neutron, a:93}, {f:items.Electron, a:64}], o:[{f:items.Gd157, a:1}]},	
	{id:'r_3y', i:[{f:items.Proton, a:64}, {f:items.Neutron, a:94}, {f:items.Electron, a:64}], o:[{f:items.Gd158, a:1}]},	
	{id:'r_3z', i:[{f:items.Proton, a:64}, {f:items.Neutron, a:96}, {f:items.Electron, a:64}], o:[{f:items.Gd160, a:1}]},	
	{id:'r_3A', i:[{f:items.Proton, a:65}, {f:items.Neutron, a:94}, {f:items.Electron, a:65}], o:[{f:items.Tb159, a:1}]},	
	{id:'r_3B', i:[{f:items.Proton, a:66}, {f:items.Neutron, a:90}, {f:items.Electron, a:66}], o:[{f:items.Dy156, a:1}]},	
	{id:'r_3C', i:[{f:items.Proton, a:66}, {f:items.Neutron, a:92}, {f:items.Electron, a:66}], o:[{f:items.Dy158, a:1}]},	
	{id:'r_3D', i:[{f:items.Proton, a:66}, {f:items.Neutron, a:94}, {f:items.Electron, a:66}], o:[{f:items.Dy160, a:1}]},	
	{id:'r_3E', i:[{f:items.Proton, a:66}, {f:items.Neutron, a:95}, {f:items.Electron, a:66}], o:[{f:items.Dy161, a:1}]},	
	{id:'r_3F', i:[{f:items.Proton, a:66}, {f:items.Neutron, a:96}, {f:items.Electron, a:66}], o:[{f:items.Dy162, a:1}]},	
	{id:'r_3G', i:[{f:items.Proton, a:66}, {f:items.Neutron, a:97}, {f:items.Electron, a:66}], o:[{f:items.Dy163, a:1}]},	
	{id:'r_3H', i:[{f:items.Proton, a:66}, {f:items.Neutron, a:98}, {f:items.Electron, a:66}], o:[{f:items.Dy164, a:1}]},	
	{id:'r_3I', i:[{f:items.Proton, a:67}, {f:items.Neutron, a:98}, {f:items.Electron, a:67}], o:[{f:items.Ho165, a:1}]},	
	{id:'r_3J', i:[{f:items.Proton, a:68}, {f:items.Neutron, a:94}, {f:items.Electron, a:68}], o:[{f:items.Er162, a:1}]},	
	{id:'r_3K', i:[{f:items.Proton, a:68}, {f:items.Neutron, a:96}, {f:items.Electron, a:68}], o:[{f:items.Er164, a:1}]},	
	{id:'r_3L', i:[{f:items.Proton, a:68}, {f:items.Neutron, a:98}, {f:items.Electron, a:68}], o:[{f:items.Er166, a:1}]},	
	{id:'r_3M', i:[{f:items.Proton, a:68}, {f:items.Neutron, a:99}, {f:items.Electron, a:68}], o:[{f:items.Er167, a:1}]},	
	{id:'r_3N', i:[{f:items.Proton, a:68}, {f:items.Neutron, a:100}, {f:items.Electron, a:68}], o:[{f:items.Er168, a:1}]},	
	{id:'r_3O', i:[{f:items.Proton, a:68}, {f:items.Neutron, a:102}, {f:items.Electron, a:68}], o:[{f:items.Er170, a:1}]},	
	{id:'r_3P', i:[{f:items.Proton, a:69}, {f:items.Neutron, a:100}, {f:items.Electron, a:69}], o:[{f:items.Tm169, a:1}]},	
	{id:'r_3Q', i:[{f:items.Proton, a:70}, {f:items.Neutron, a:98}, {f:items.Electron, a:70}], o:[{f:items.Yb168, a:1}]},	
	{id:'r_3R', i:[{f:items.Proton, a:70}, {f:items.Neutron, a:100}, {f:items.Electron, a:70}], o:[{f:items.Yb170, a:1}]},	
	{id:'r_3S', i:[{f:items.Proton, a:70}, {f:items.Neutron, a:101}, {f:items.Electron, a:70}], o:[{f:items.Yb171, a:1}]},	
	{id:'r_3T', i:[{f:items.Proton, a:70}, {f:items.Neutron, a:102}, {f:items.Electron, a:70}], o:[{f:items.Yb172, a:1}]},	
	{id:'r_3U', i:[{f:items.Proton, a:70}, {f:items.Neutron, a:103}, {f:items.Electron, a:70}], o:[{f:items.Yb173, a:1}]},	
	{id:'r_3V', i:[{f:items.Proton, a:70}, {f:items.Neutron, a:104}, {f:items.Electron, a:70}], o:[{f:items.Yb174, a:1}]},	
	{id:'r_3W', i:[{f:items.Proton, a:70}, {f:items.Neutron, a:106}, {f:items.Electron, a:70}], o:[{f:items.Yb176, a:1}]},	
	{id:'r_3X', i:[{f:items.Proton, a:71}, {f:items.Neutron, a:104}, {f:items.Electron, a:71}], o:[{f:items.Lu175, a:1}]},	
	{id:'r_3Y', i:[{f:items.Proton, a:71}, {f:items.Neutron, a:105}, {f:items.Electron, a:71}], o:[{f:items.Lu176, a:1}]},	
	{id:'r_3Z', i:[{f:items.Proton, a:72}, {f:items.Neutron, a:102}, {f:items.Electron, a:72}], o:[{f:items.Hf174, a:1}]},	
	{id:'r_40', i:[{f:items.Proton, a:72}, {f:items.Neutron, a:104}, {f:items.Electron, a:72}], o:[{f:items.Hf176, a:1}]},	
	{id:'r_41', i:[{f:items.Proton, a:72}, {f:items.Neutron, a:105}, {f:items.Electron, a:72}], o:[{f:items.Hf177, a:1}]},	
	{id:'r_42', i:[{f:items.Proton, a:72}, {f:items.Neutron, a:106}, {f:items.Electron, a:72}], o:[{f:items.Hf178, a:1}]},	
	{id:'r_43', i:[{f:items.Proton, a:72}, {f:items.Neutron, a:107}, {f:items.Electron, a:72}], o:[{f:items.Hf179, a:1}]},	
	{id:'r_44', i:[{f:items.Proton, a:72}, {f:items.Neutron, a:108}, {f:items.Electron, a:72}], o:[{f:items.Hf180, a:1}]},	
	{id:'r_45', i:[{f:items.Proton, a:73}, {f:items.Neutron, a:108}, {f:items.Electron, a:73}], o:[{f:items.Ta181, a:1}]},	
	{id:'r_46', i:[{f:items.Proton, a:74}, {f:items.Neutron, a:106}, {f:items.Electron, a:74}], o:[{f:items.W180, a:1}]},	
	{id:'r_47', i:[{f:items.Proton, a:74}, {f:items.Neutron, a:108}, {f:items.Electron, a:74}], o:[{f:items.W182, a:1}]},	
	{id:'r_48', i:[{f:items.Proton, a:74}, {f:items.Neutron, a:109}, {f:items.Electron, a:74}], o:[{f:items.W183, a:1}]},	
	{id:'r_49', i:[{f:items.Proton, a:74}, {f:items.Neutron, a:110}, {f:items.Electron, a:74}], o:[{f:items.W184, a:1}]},	
	{id:'r_4a', i:[{f:items.Proton, a:74}, {f:items.Neutron, a:112}, {f:items.Electron, a:74}], o:[{f:items.W186, a:1}]},	
	{id:'r_4b', i:[{f:items.Proton, a:75}, {f:items.Neutron, a:110}, {f:items.Electron, a:75}], o:[{f:items.Re185, a:1}]},	
	{id:'r_4c', i:[{f:items.Proton, a:75}, {f:items.Neutron, a:112}, {f:items.Electron, a:75}], o:[{f:items.Re187, a:1}]},	
	{id:'r_4d', i:[{f:items.Proton, a:76}, {f:items.Neutron, a:108}, {f:items.Electron, a:76}], o:[{f:items.Os184, a:1}]},	
	{id:'r_4e', i:[{f:items.Proton, a:76}, {f:items.Neutron, a:110}, {f:items.Electron, a:76}], o:[{f:items.Os186, a:1}]},	
	{id:'r_4f', i:[{f:items.Proton, a:76}, {f:items.Neutron, a:111}, {f:items.Electron, a:76}], o:[{f:items.Os187, a:1}]},	
	{id:'r_4g', i:[{f:items.Proton, a:76}, {f:items.Neutron, a:112}, {f:items.Electron, a:76}], o:[{f:items.Os188, a:1}]},	
	{id:'r_4h', i:[{f:items.Proton, a:76}, {f:items.Neutron, a:113}, {f:items.Electron, a:76}], o:[{f:items.Os189, a:1}]},	
	{id:'r_4i', i:[{f:items.Proton, a:76}, {f:items.Neutron, a:114}, {f:items.Electron, a:76}], o:[{f:items.Os190, a:1}]},	
	{id:'r_4j', i:[{f:items.Proton, a:76}, {f:items.Neutron, a:116}, {f:items.Electron, a:76}], o:[{f:items.Os192, a:1}]},	
	{id:'r_4k', i:[{f:items.Proton, a:77}, {f:items.Neutron, a:114}, {f:items.Electron, a:77}], o:[{f:items.Ir191, a:1}]},	
	{id:'r_4l', i:[{f:items.Proton, a:77}, {f:items.Neutron, a:116}, {f:items.Electron, a:77}], o:[{f:items.Ir193, a:1}]},	
	{id:'r_4m', i:[{f:items.Proton, a:78}, {f:items.Neutron, a:112}, {f:items.Electron, a:78}], o:[{f:items.Pt190, a:1}]},	
	{id:'r_4n', i:[{f:items.Proton, a:78}, {f:items.Neutron, a:114}, {f:items.Electron, a:78}], o:[{f:items.Pt192, a:1}]},	
	{id:'r_4o', i:[{f:items.Proton, a:78}, {f:items.Neutron, a:116}, {f:items.Electron, a:78}], o:[{f:items.Pt194, a:1}]},	
	{id:'r_4p', i:[{f:items.Proton, a:78}, {f:items.Neutron, a:117}, {f:items.Electron, a:78}], o:[{f:items.Pt195, a:1}]},	
	{id:'r_4q', i:[{f:items.Proton, a:78}, {f:items.Neutron, a:118}, {f:items.Electron, a:78}], o:[{f:items.Pt196, a:1}]},	
	{id:'r_4r', i:[{f:items.Proton, a:78}, {f:items.Neutron, a:120}, {f:items.Electron, a:78}], o:[{f:items.Pt198, a:1}]},	
	{id:'r_4s', i:[{f:items.Proton, a:79}, {f:items.Neutron, a:118}, {f:items.Electron, a:79}], o:[{f:items.Au197, a:1}]},	
	{id:'r_4t', i:[{f:items.Proton, a:80}, {f:items.Neutron, a:116}, {f:items.Electron, a:80}], o:[{f:items.Hg196, a:1}]},	
	{id:'r_4u', i:[{f:items.Proton, a:80}, {f:items.Neutron, a:118}, {f:items.Electron, a:80}], o:[{f:items.Hg198, a:1}]},	
	{id:'r_4v', i:[{f:items.Proton, a:80}, {f:items.Neutron, a:119}, {f:items.Electron, a:80}], o:[{f:items.Hg199, a:1}]},	
	{id:'r_4w', i:[{f:items.Proton, a:80}, {f:items.Neutron, a:120}, {f:items.Electron, a:80}], o:[{f:items.Hg200, a:1}]},	
	{id:'r_4x', i:[{f:items.Proton, a:80}, {f:items.Neutron, a:121}, {f:items.Electron, a:80}], o:[{f:items.Hg201, a:1}]},	
	{id:'r_4y', i:[{f:items.Proton, a:80}, {f:items.Neutron, a:122}, {f:items.Electron, a:80}], o:[{f:items.Hg202, a:1}]},	
	{id:'r_4z', i:[{f:items.Proton, a:80}, {f:items.Neutron, a:124}, {f:items.Electron, a:80}], o:[{f:items.Hg204, a:1}]},	
	{id:'r_4A', i:[{f:items.Proton, a:81}, {f:items.Neutron, a:122}, {f:items.Electron, a:81}], o:[{f:items.Tl203, a:1}]},	
	{id:'r_4B', i:[{f:items.Proton, a:81}, {f:items.Neutron, a:124}, {f:items.Electron, a:81}], o:[{f:items.Tl205, a:1}]},	
	{id:'r_4C', i:[{f:items.Proton, a:82}, {f:items.Neutron, a:122}, {f:items.Electron, a:82}], o:[{f:items.Pb204, a:1}]},	
	{id:'r_4D', i:[{f:items.Proton, a:82}, {f:items.Neutron, a:124}, {f:items.Electron, a:82}], o:[{f:items.Pb206, a:1}]},	
	{id:'r_4E', i:[{f:items.Proton, a:82}, {f:items.Neutron, a:125}, {f:items.Electron, a:82}], o:[{f:items.Pb207, a:1}]},	
	{id:'r_4F', i:[{f:items.Proton, a:82}, {f:items.Neutron, a:126}, {f:items.Electron, a:82}], o:[{f:items.Pb208, a:1}]},	
	{id:'r_4G', i:[{f:items.Proton, a:83}, {f:items.Neutron, a:126}, {f:items.Electron, a:83}], o:[{f:items.Bi209, a:1}]},	
	{id:'r_4H', i:[{f:items.Proton, a:84}, {f:items.Neutron, a:125}, {f:items.Electron, a:84}], o:[{f:items.Po209, a:1}]},	
	{id:'r_4I', i:[{f:items.Proton, a:85}, {f:items.Neutron, a:125}, {f:items.Electron, a:85}], o:[{f:items.At210, a:1}]},	
	{id:'r_4J', i:[{f:items.Proton, a:86}, {f:items.Neutron, a:136}, {f:items.Electron, a:86}], o:[{f:items.Rn222, a:1}]},	
	{id:'r_4K', i:[{f:items.Proton, a:87}, {f:items.Neutron, a:136}, {f:items.Electron, a:87}], o:[{f:items.Fr223, a:1}]},	
	{id:'r_4L', i:[{f:items.Proton, a:88}, {f:items.Neutron, a:138}, {f:items.Electron, a:88}], o:[{f:items.Ra226, a:1}]},	
	{id:'r_4M', i:[{f:items.Proton, a:89}, {f:items.Neutron, a:138}, {f:items.Electron, a:89}], o:[{f:items.Ac227, a:1}]},	
	{id:'r_4N', i:[{f:items.Proton, a:90}, {f:items.Neutron, a:142}, {f:items.Electron, a:90}], o:[{f:items.Th232, a:1}]},	
	{id:'r_4O', i:[{f:items.Proton, a:91}, {f:items.Neutron, a:140}, {f:items.Electron, a:91}], o:[{f:items.Pa231, a:1}]},	
	{id:'r_4P', i:[{f:items.Proton, a:92}, {f:items.Neutron, a:142}, {f:items.Electron, a:92}], o:[{f:items.U234, a:1}]},	
	{id:'r_4Q', i:[{f:items.Proton, a:92}, {f:items.Neutron, a:143}, {f:items.Electron, a:92}], o:[{f:items.U235, a:1}]},	
	{id:'r_4R', i:[{f:items.Proton, a:92}, {f:items.Neutron, a:146}, {f:items.Electron, a:92}], o:[{f:items.U238, a:1}]},	
	{id:'r_4S', i:[{f:items.Proton, a:93}, {f:items.Neutron, a:144}, {f:items.Electron, a:93}], o:[{f:items.Np237, a:1}]},	
	{id:'r_4T', i:[{f:items.Proton, a:94}, {f:items.Neutron, a:150}, {f:items.Electron, a:94}], o:[{f:items.Pu244, a:1}]},	
	{id:'r_4U', i:[{f:items.Proton, a:95}, {f:items.Neutron, a:148}, {f:items.Electron, a:95}], o:[{f:items.Am243, a:1}]},	
	{id:'r_4V', i:[{f:items.Proton, a:96}, {f:items.Neutron, a:151}, {f:items.Electron, a:96}], o:[{f:items.Cm247, a:1}]},	
	{id:'r_4W', i:[{f:items.Proton, a:97}, {f:items.Neutron, a:150}, {f:items.Electron, a:97}], o:[{f:items.Bk247, a:1}]},	
	{id:'r_4X', i:[{f:items.Proton, a:98}, {f:items.Neutron, a:153}, {f:items.Electron, a:98}], o:[{f:items.Cf251, a:1}]},	
	{id:'r_4Y', i:[{f:items.Proton, a:99}, {f:items.Neutron, a:153}, {f:items.Electron, a:99}], o:[{f:items.Es252, a:1}]},	
	{id:'r_4Z', i:[{f:items.Proton, a:100}, {f:items.Neutron, a:157}, {f:items.Electron, a:100}], o:[{f:items.Fm257, a:1}]},	
	{id:'r_50', i:[{f:items.Proton, a:101}, {f:items.Neutron, a:157}, {f:items.Electron, a:101}], o:[{f:items.Md258, a:1}]},	
	{id:'r_51', i:[{f:items.Proton, a:102}, {f:items.Neutron, a:159}, {f:items.Electron, a:102}], o:[{f:items.No261, a:1}]},	
	{id:'r_52', i:[{f:items.Proton, a:103}, {f:items.Neutron, a:161}, {f:items.Electron, a:103}], o:[{f:items.Lr264, a:1}]},	
	{id:'r_53', i:[{f:items.Proton, a:104}, {f:items.Neutron, a:161}, {f:items.Electron, a:104}], o:[{f:items.Rf265, a:1}]},	
	{id:'r_54', i:[{f:items.Proton, a:105}, {f:items.Neutron, a:163}, {f:items.Electron, a:105}], o:[{f:items.Db268, a:1}]},	
	{id:'r_55', i:[{f:items.Proton, a:106}, {f:items.Neutron, a:165}, {f:items.Electron, a:106}], o:[{f:items.Sg271, a:1}]},	
	{id:'r_56', i:[{f:items.Proton, a:107}, {f:items.Neutron, a:166}, {f:items.Electron, a:107}], o:[{f:items.Bh273, a:1}]},	
	{id:'r_57', i:[{f:items.Proton, a:108}, {f:items.Neutron, a:168}, {f:items.Electron, a:108}], o:[{f:items.Hs276, a:1}]},	
	{id:'r_58', i:[{f:items.Proton, a:109}, {f:items.Neutron, a:167}, {f:items.Electron, a:109}], o:[{f:items.Mt278, a:1}]},	
	{id:'r_59', i:[{f:items.Proton, a:110}, {f:items.Neutron, a:171}, {f:items.Electron, a:110}], o:[{f:items.Ds281, a:1}]},	
	{id:'r_5a', i:[{f:items.Proton, a:111}, {f:items.Neutron, a:172}, {f:items.Electron, a:111}], o:[{f:items.Rg283, a:1}]},	
	{id:'r_5b', i:[{f:items.Proton, a:112}, {f:items.Neutron, a:173}, {f:items.Electron, a:112}], o:[{f:items.Cn285, a:1}]},	
	{id:'r_5c', i:[{f:items.Proton, a:113}, {f:items.Neutron, a:174}, {f:items.Electron, a:113}], o:[{f:items.Nh287, a:1}]},	
	{id:'r_5d', i:[{f:items.Proton, a:114}, {f:items.Neutron, a:175}, {f:items.Electron, a:114}], o:[{f:items.Fl289, a:1}]},	
	{id:'r_5e', i:[{f:items.Proton, a:115}, {f:items.Neutron, a:176}, {f:items.Electron, a:115}], o:[{f:items.Mc291, a:1}]},	
	{id:'r_5f', i:[{f:items.Proton, a:116}, {f:items.Neutron, a:176}, {f:items.Electron, a:116}], o:[{f:items.Lv292, a:1}]},	
	{id:'r_5g', i:[{f:items.Proton, a:117}, {f:items.Neutron, a:175}, {f:items.Electron, a:117}], o:[{f:items.Ts292, a:1}]},	
	{id:'r_5h', i:[{f:items.Proton, a:118}, {f:items.Neutron, a:175}, {f:items.Electron, a:118}], o:[{f:items.Og293, a:1}]},	

//organic
	{id:'r_5i', i:[{f:items.H1, a:2}], o:[{f:items.dihydrogen, a:1}]},	
	{id:'r_5j', i:[{f:items.H2, a:2}], o:[{f:items.deuteratedDihydrogen, a:1}]},	
	{id:'r_5k', i:[{f:items.O16, a:2}], o:[{f:items.dioxygen, a:1}]},	
	{id:'r_5l', i:[{f:items.H1, a:3}, {f:items.N14, a:1}], o:[{f:items.ammonia, a:1}]},	
	{id:'r_5m', i:[{f:items.H1, a:2}, {f:items.O16, a:1}], o:[{f:items.water, a:1}]},	
	{id:'r_5n', i:[{f:items.H1, a:3}, {f:items.O16, a:1}], o:[{f:items.hydronium, a:1}]},	
	{id:'r_5o', i:[{f:items.C12, a:1}, {f:items.O16, a:1}], o:[{f:items.carbonMonoxide, a:1}]},	
	{id:'r_5p', i:[{f:items.C12, a:1}, {f:items.O16, a:2}], o:[{f:items.carbonDioxide, a:1}]},	
	{id:'r_5q', i:[{f:items.C12, a:1}, {f:items.H1, a:4}], o:[{f:items.methane, a:1}]},	
	{id:'r_5r', i:[{f:items.C12, a:2}, {f:items.H1, a:6}], o:[{f:items.ethane, a:1}]},	
	{id:'r_5s', i:[{f:items.C12, a:3}, {f:items.H1, a:8}], o:[{f:items.propane, a:1}]},	
	{id:'r_5t', i:[{f:items.C12, a:4}, {f:items.H1, a:10}], o:[{f:items.butane, a:1}]},	
	{id:'r_5u', i:[{f:items.C12, a:1}, {f:items.H1, a:2}], o:[{f:items.methene, a:1}]},	
	{id:'r_5v', i:[{f:items.C12, a:2}, {f:items.H1, a:4}], o:[{f:items.ethene, a:1}]},	
	{id:'r_5w', i:[{f:items.C12, a:3}, {f:items.H1, a:6}], o:[{f:items.propene, a:1}]},	
	{id:'r_5x', i:[{f:items.C12, a:4}, {f:items.H1, a:8}], o:[{f:items.butene, a:1}]},	
	{id:'r_5y', i:[{f:items.C12, a:2}, {f:items.H1, a:2}], o:[{f:items.ethyne, a:1}]},	
	{id:'r_5z', i:[{f:items.C12, a:3}, {f:items.H1, a:4}], o:[{f:items.propyne, a:1}]},	
	{id:'r_5A', i:[{f:items.C12, a:4}, {f:items.H1, a:6}], o:[{f:items.butyne, a:1}]},	
	{id:'r_5B', i:[{f:items.C12, a:6}, {f:items.H1, a:6}], o:[{f:items.benzene, a:1}]},	
	{id:'r_5C', i:[{f:items.carbonMonoxide, a:1}, {f:items.dihydrogen, a:2}], o:[{f:items.methanol, a:1}]},	
	{id:'r_5D', i:[{f:items.ethene, a:1}, {f:items.water, a:1}], o:[{f:items.ethanol, a:1}]},	
	{id:'r_5E', i:[{f:items.ethene, a:1}, {f:items.carbonMonoxide, a:1}, {f:items.dihydrogen, a:1}], o:[{f:items.propanol, a:1}]},	
	{id:'r_5F', i:[{f:items.benzene, a:1}, {f:items.methanol, a:1}], o:[{f:items.toluene, a:1}, {f:items.water, a:1}]},	
	{id:'r_5G', i:[{f:items.methanol, a:1}, {f:items.carbonMonoxide, a:1}], o:[{f:items.aceticAcid, a:1}]},	
	{id:'r_5H', i:[{f:items.carbonDioxide, a:1}, {f:items.dihydrogen, a:2}], o:[{f:items.formicAcid, a:1}]},	
	{id:'r_5I', i:[{f:items.toluene, a:2}, {f:items.dioxygen, a:3}], o:[{f:items.benzoicAcid, a:2}, {f:items.water, a:2}]},	
	{id:'r_5J', i:[{f:items.aceticAcid, a:1}, {f:items.ammonia, a:1}], o:[{f:items.acetamide, a:1}, {f:items.water, a:1}]},	
	{id:'r_5K', i:[{f:items.benzoicAcid, a:1}, {f:items.ammonia, a:1}], o:[{f:items.benzamide, a:1}, {f:items.water, a:1}]},	
	{id:'r_5L', i:[{f:items.ammonia, a:1}, {f:items.methanol, a:1}], o:[{f:items.methylamine, a:1}, {f:items.water, a:1}]},	
	{id:'r_5M', i:[{f:items.ammonia, a:1}, {f:items.methanol, a:2}], o:[{f:items.dimethylamine, a:1}, {f:items.water, a:2}]},	
	{id:'r_5N', i:[{f:items.ammonia, a:1}, {f:items.methanol, a:3}], o:[{f:items.trimethylamine, a:1}, {f:items.water, a:3}]},	
	{id:'r_5O', i:[{f:items.carbonDioxide, a:6}, {f:items.water, a:6}, {f:items.Photon, a:100}], o:[{f:items.glucose, a:1}, {f:items.dioxygen, a:6}]},
	{id:'r_5P', i:[{f:items.C12, a:1}, {f:items.H1, a:4}, {f:items.O16, a:1}], o:[{f:items.methanol, a:1}]},	
	{id:'r_5Q', i:[{f:items.C12, a:2}, {f:items.H1, a:6}, {f:items.O16, a:1}], o:[{f:items.ethanol, a:1}]},	
	{id:'r_5R', i:[{f:items.C12, a:3}, {f:items.H1, a:8}, {f:items.O16, a:1}], o:[{f:items.propanol, a:1}]},	
	{id:'r_5S', i:[{f:items.C12, a:7}, {f:items.H1, a:8}], o:[{f:items.toluene, a:1}]},	
	{id:'r_5T', i:[{f:items.C12, a:2}, {f:items.H1, a:3}, {f:items.O16, a:2}], o:[{f:items.aceticAcid, a:1}]},	
	{id:'r_5U', i:[{f:items.C12, a:1}, {f:items.H1, a:2}, {f:items.O16, a:2}], o:[{f:items.formicAcid, a:1}]},	
	{id:'r_5V', i:[{f:items.C12, a:7}, {f:items.H1, a:6}, {f:items.O16, a:2}], o:[{f:items.benzoicAcid, a:1}]},	
	{id:'r_5W', i:[{f:items.C12, a:2}, {f:items.H1, a:5}, {f:items.N14, a:1}, {f:items.O16, a:1}], o:[{f:items.acetamide, a:1}]},	
	{id:'r_5X', i:[{f:items.C12, a:7}, {f:items.H1, a:7}, {f:items.N14, a:1}, {f:items.O16, a:1}], o:[{f:items.benzamide, a:1}]},	
	{id:'r_5Y', i:[{f:items.C12, a:1}, {f:items.H1, a:5}, {f:items.N14, a:1}], o:[{f:items.methylamine, a:1}]},	
	{id:'r_5Z', i:[{f:items.C12, a:2}, {f:items.H1, a:7}, {f:items.N14, a:1}], o:[{f:items.dimethylamine, a:1}]},	
	{id:'r_60', i:[{f:items.C12, a:3}, {f:items.H1, a:9}, {f:items.N14, a:1}], o:[{f:items.trimethylamine, a:1}]},	
	{id:'r_61', i:[{f:items.C12, a:6}, {f:items.H1, a:12}, {f:items.O16, a:6}], o:[{f:items.glucose, a:1}]},	
	{id:'r_62', i:[{f:items.carbonDioxide, a:6}, {f:items.water, a:6}, {f:items.Photon, a:100}], o:[{f:items.fructose, a:1}, {f:items.dioxygen, a:6}]},	
	{id:'r_63', i:[{f:items.C12, a:6}, {f:items.H1, a:12}, {f:items.O16, a:6}], o:[{f:items.fructose, a:1}]},	
	{id:'r_64', i:[{f:items.C12, a:5}, {f:items.H1, a:10}, {f:items.O16, a:5}], o:[{f:items.ribose, a:1}]},	
	{id:'r_65', i:[{f:items.glucose, a:1}, {f:items.fructose, a:1}], o:[{f:items.sucrose, a:1}, {f:items.water, a:1}]},	
	{id:'r_66', i:[{f:items.glucose, a:5000}], o:[{f:items.cellulose, a:1}, {f:items.water, a:4999}]},	
	{id:'r_67', i:[{f:items.glucose, a:10000}], o:[{f:items.glycogen, a:1}]},	
	{id:'r_68', i:[{f:items.C12, a:5}, {f:items.H1, a:10}, {f:items.O16, a:5}], o:[{f:items.xylose, a:1}]},	
	{id:'r_69', i:[{f:items.C12, a:6}, {f:items.H1, a:12}, {f:items.O16, a:6}], o:[{f:items.mannose, a:1}]},	
	{id:'r_6a', i:[{f:items.C12, a:6}, {f:items.H1, a:12}, {f:items.O16, a:6}], o:[{f:items.galactose, a:1}]},	
	{id:'r_6b', i:[{f:items.C12, a:5}, {f:items.H1, a:10}, {f:items.O16, a:5}], o:[{f:items.arabinose, a:1}]},	
	{id:'r_6c', i:[{f:items.xylose, a:900}, {f:items.mannose, a:750}, {f:items.galactose, a:750}, {f:items.arabinose, a:450}, {f:items.glucose, a:150}], o:[{f:items.hemicellulose, a:1}]},
	{id:'r_6d', i:[{f:items.C12, a:9}, {f:items.H1, a:11}, {f:items.N14, a:1}, {f:items.O16, a:2}], o:[{f:items.phenylalanine, a:1}]},
	{id:'r_6e', i:[{f:items.phenylalanine, a:1}, {f:items.dioxygen, a:1}, {f:items.H1, a:3}], o:[{f:items.coniferylAlcohol, a:1}, {f:items.water, a:1}, {f:items.ammonia, a:1}]},
	{id:'r_6f', i:[{f:items.phenylalanine, a:1}, {f:items.dioxygen, a:1}, {f:items.H1, a:6}, {f:items.C12, a:2}], o:[{f:items.sinapylAlcohol, a:1}, {f:items.ammonia, a:1}]},
	{id:'r_6g', i:[{f:items.phenylalanine, a:1}, {f:items.H1, a:2}], o:[{f:items.coumerylAlcohol, a:1}, {f:items.ammonia, a:1}]},
	{id:'r_6h', i:[{f:items.coniferylAlcohol, a:60}, {f:items.sinapylAlcohol, a:30}, {f:items.coumerylAlcohol, a:10}], o:[{f:items.hardLignin, a:1}]},
	{id:'r_6i', i:[{f:items.coniferylAlcohol, a:10}, {f:items.sinapylAlcohol, a:90}], o:[{f:items.softLignin, a:1}]},
	{id:'r_6j', i:[{f:items.cellulose, a:10}, {f:items.hemicellulose, a:1}, {f:items.hardLignin, a:20}], o:[{f:items.hardwoodParticle, a:1}]},
	{id:'r_6k', i:[{f:items.cellulose, a:8}, {f:items.hemicellulose, a:1}, {f:items.softLignin, a:20}], o:[{f:items.softwoodParticle, a:1}]},
	{id:'r_6l', i:[{f:items.H2, a:2}, {f:items.O16, a:1}], o:[{f:items.heavyWater, a:1}]},	
	{id:'r_6m', i:[{f:items.H3, a:2}, {f:items.O16, a:1}], o:[{f:items.tritiatedWater, a:1}]},
	{id:'r_6n', i:[{f:items.C12, a:1}, {f:items.H1, a:2}, {f:items.O16, a:1}], o:[{f:items.formeldehyde, a:1}]},
	{id:'r_6o', i:[{f:items.methanol, a:2}, {f:items.dioxygen, a:1}], o:[{f:items.formeldehyde, a:2}, {f:items.water, a:2}]},
	{id:'r_6p', i:[{f:items.C12, a:6}, {f:items.H1, a:6}, {f:items.O16, a:1}], o:[{f:items.phenol, a:1}]},
	{id:'r_6q', i:[{f:items.benzene, a:1}, {f:items.O16, a:1}], o:[{f:items.phenol, a:1}]},
	{id:'r_6r', i:[{f:items.toluene, a:1}, {f:items.dioxygen, a:2}], o:[{f:items.phenol, a:1}, {f:items.carbonDioxide, a:1}, {f:items.water, a:1}]},
	

//inorganic
	{id:'r_6s', i:[{f:items.H1, a:1}, {f:items.Cl35, a:1}], o:[{f:items.HCl, a:1}]},	
	{id:'r_6t', i:[{f:items.H1, a:2}, {f:items.O16, a:4}, {f:items.S32, a:1}], o:[{f:items.H2SO4, a:1}]},	
	{id:'r_6u', i:[{f:items.H1, a:1}, {f:items.O16, a:1}, {f:items.Na23, a:1}], o:[{f:items.NaOH, a:1}]},	
	{id:'r_6v', i:[{f:items.H1, a:1}, {f:items.O16, a:1}, {f:items.K39, a:1}], o:[{f:items.KOH, a:1}]},	
	{id:'r_6w', i:[{f:items.HCl, a:1}, {f:items.NaOH, a:1}], o:[{f:items.NaCl, a:1}, {f:items.water, a:1}]},	
	{id:'r_6x', i:[{f:items.HCl, a:1}, {f:items.KOH, a:1}], o:[{f:items.KCl, a:1}, {f:items.water, a:1}]},	
	{id:'r_6y', i:[{f:items.C12, a:1 }, {f:items.Fe56, a:100 }], o:[{f:items.mildSteel, a:1}]},	
	{id:'r_6z', i:[{f:items.C12, a:5 }, {f:items.Fe56, a:100 }], o:[{f:items.highSteel, a:1}]},	
	{id:'r_6A', i:[{f:items.Na23, a:2}, {f:items.S32, a:1}], o:[{f:items.Na2S, a:1}]},	
	{id:'r_6B', i:[{f:items.Na23, a:2}, {f:items.S32, a:1}, {f:items.O16, a:4}], o:[{f:items.Na2SO4, a:1}]},	
	{id:'r_6C', i:[{f:items.Na2SO4, a:1}, {f:items.C12, a:2}], o:[{f:items.Na2S, a:1}, {f:items.carbonDioxide, a:2}]},	
	{id:'r_6D', i:[{f:items.C12, b:new Amount({Da:12}) }, {f:items.Fe56, b:new Amount({Da:5600})}], o:[{f:items.mildSteel, a:1}]},	
	{id:'r_6E', i:[{f:items.C12, b:new Amount({Da:60}) }, {f:items.Fe56, b:new Amount({Da:5600})}], o:[{f:items.highSteel, a:1}]},	
	
//human wood
	{id:'r_6F', i:[{f:items.hardwoodParticle, a:64000000}], o:[{f:items.hardwoodFiber, a:1}]},
	{id:'r_6G', i:[{f:items.softwoodParticle, a:64000000}], o:[{f:items.softwoodFiber, a:1}]},
	{id:'r_6H', i:[{f:items.hardwoodFiber, a:640000000}], o:[{f:items.hardwoodChip, a:1}]},
	{id:'r_6I', i:[{f:items.softwoodFiber, a:420000000}], o:[{f:items.softwoodChip, a:1}]},
	{id:'r_6J', i:[{f:items.hardwoodChip, a:5}, {f:items.whiteLiquor, a:10}], o:[{f:items.hardwoodPulp, a:6}, {f:items.blackLiquor, a:4}]},
	{id:'r_6K', i:[{f:items.softwoodChip, a:5}, {f:items.whiteLiquor, a:10}], o:[{f:items.softwoodPulp, a:6}, {f:items.blackLiquor, a:4}]},
	{id:'r_6L', i:[{f:items.hardwoodChip, a:3625}], o:[{f:items.hardwood5x10x3, a:1}]},
	{id:'r_6M', i:[{f:items.softwoodChip, a:4100}], o:[{f:items.softwood5x10x3, a:1}]},
	{id:'r_71', i:[{f:items.hardwoodChip, a:9440}], o:[{f:items.hardPly12, a:1}]},
	{id:'r_72', i:[{f:items.softwoodChip, a:16992}], o:[{f:items.softPly12, a:1}]},

//human Industrial Paper
	{id:'r_6N', i:[{f:items.water, a:22380000000}, {f:items.NaOH, a:1865000000}, {f:items.Na2S, a:373000000}], o:[{f:items.whiteLiquorMote, a:1}]},
	{id:'r_6O', i:[{f:items.water, b:new Amount({Da:402840000000})}, {f:items.NaOH, b:new Amount({Da:145470000000})}, {f:items.Na2S, b:new Amount({Da:52966000000})}], o:[{f:items.whiteLiquorMote, a:1}]},
	{id:'r_6P', i:[{f:items.whiteLiquorMote, a:1000000000000}], o:[{f:items.whiteLiquorMote, a:1}]},
	{id:'r_6Q', i:[{f:items.whiteLiquorMote, b:new Amount({g:1})}], o:[{f:items.whiteLiquor, a:1}]},
	{id:'r_6R', i:[{f:items.softwoodPulp, a:4}, {f:items.water, b:new Amount({g:30})}], o:[{f:items.paperA4, a:1}]},
	{id:'r_6S', i:[{f:items.hardwoodPulp, a:2}, {f:items.water, b:new Amount({g:30})}], o:[{f:items.paperA4, a:1}]},
	{id:'r_6T', i:[{f:items.softwoodPulp, a:8}, {f:items.water, b:new Amount({g:30})}], o:[{f:items.paperA3, a:1}]},
	{id:'r_6U', i:[{f:items.hardwoodPulp, a:4}, {f:items.water, b:new Amount({g:30})}], o:[{f:items.paperA3, a:1}]},
	{id:'r_6V', i:[{f:items.softwoodPulp, a:16}, {f:items.water, b:new Amount({g:30})}], o:[{f:items.paperA2, a:1}]},
	{id:'r_6W', i:[{f:items.hardwoodPulp, a:8}, {f:items.water, b:new Amount({g:30})}], o:[{f:items.paperA2, a:1}]},
	{id:'r_6X', i:[{f:items.softwoodPulp, a:32}, {f:items.water, b:new Amount({g:30})}], o:[{f:items.paperA1, a:1}]},
	{id:'r_6Y', i:[{f:items.hardwoodPulp, a:16}, {f:items.water, b:new Amount({g:30})}], o:[{f:items.paperA1, a:1}]},
	{id:'r_6Z', i:[{f:items.softwoodPulp, a:64}, {f:items.water, b:new Amount({g:30})}], o:[{f:items.paperA0, a:1}]},
	{id:'r_70', i:[{f:items.hardwoodPulp, a:32}, {f:items.water, b:new Amount({g:30})}], o:[{f:items.paperA0, a:1}]},
];
